version: "3.4"

services:          
    rental-manager-api:
        environment:
          - TZ=Europe/Warsaw
        image: "marchewjapko/rental-manager-api:latest"
        ports:
          - "8080:80"
        depends_on:
          - system-monitor-db
          
    system-monitor-db:
        environment:
          - TZ=Europe/Warsaw
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1450:1433"

        environment:
            MSSQL_SA_PASSWORD: "2620dvxje!ABC"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: True