version: "3.4"

services:          
    rental-manager-api:
        environment:
          - TZ=Europe/Warsaw
        image: "marchewjapko/rental-manager-api:latest"
        ports:
          - "8080:80"
        depends_on:
          - rental-manager-db

    rental-manager-document-service:
        environment:
          - TZ=Europe/Warsaw
        image: "marchewjapko/rental-manager-document-service:latest"
        ports:
          - "8081:80"
          
    rental-manager-db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        user: root
        ports:
          - "1450:1433"
        volumes:
          - "database-vol:/var/opt/mssql"
        deploy:
          mode: global
        environment:
            TZ: "Europe/Warsaw"
            MSSQL_SA_PASSWORD: "2620dvxje!ABC"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: True
volumes:
  database-vol: