import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import ThemeRegistry from "@/src/ThemeRegistry/ThemeRegistry";
import RecoilProvider from "@/src/RecoilProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<RecoilProvider>
					<ThemeRegistry>{children}</ThemeRegistry>
				</RecoilProvider>
			</body>
		</html>
	);
}
