name: Coverlet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Get-Code-Coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore "WebApi/RentalManager.WebAPI/RentalManager.WebAPI.csproj"

      - name: Build the Project
        run: dotnet build --configuration Release --property WarningLevel=0 "WebApi/RentalManager.WebAPI/RentalManager.WebAPI.csproj"

      - name: Clear NuGet Cache
        run: dotnet nuget locals all --clear

      - name: Run Tests with Coverage
        run: dotnet test --results-directory WebApi/RentalManager.Tests/TestResults --collect:"XPlat Code Coverage" "WebApi/RentalManager.Tests/RentalManager.Tests.csproj"

      - name: Copy Test Results
        run: cp WebApi/RentalManager.Tests/TestResults/*/coverage.cobertura.xml ./coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: "./coverage.xml"

  Get-Custom-Badge:
    needs: Get-Code-Coverage
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - name: Download File
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - name: Use File
        id: file-parse
        run: xml_file="./coverage.xml"; line_rate=$(grep -oP 'line-rate="\K[^"]+' "$xml_file"| head -1); echo "web-api-code-coverage=$line_rate" >> "$GITHUB_OUTPUT"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: test
          LABEL: 'Test?'
          STATUS: ${{ steps.file-parse.outputs.web-api-code-coverage }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
