name: Coverlet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "WebApi/RentalManager.WebAPI/RentalManager.WebAPI.csproj"

      - name: Build the project
        run: dotnet build --configuration Release --property WarningLevel=0 "WebApi/RentalManager.WebAPI/RentalManager.WebAPI.csproj"

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Run tests with coverage
        run: dotnet test --results-directory WebApi/RentalManager.Tests/TestResults --collect:"XPlat Code Coverage" "WebApi/RentalManager.Tests/RentalManager.Tests.csproj"
        
      - name: Where is it
        run: ls
                
      - name: Where is it2
        run: ls WebApi/RentalManager.Tests
                        
      - name: Where is it3
        run: ls WebApi
                        
      - name: Where is it4
        run: ls WebApi/RentalManager.Tests/TestResults

      - name: Copy test result
        run: cp WebApi/RentalManager.Tests/TestResults/*/coverage.cobertura.xml ./coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: "./coverage.xml"
