name: Coverlet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Run tests with coverage
        uses: b3b00/coverlet-action@1.3.0
        with:
          testProject: "WebApi/RentalManager.Tests/RentalManager.Tests.csproj"
          configuration: 'Release'
          output: 'cobertura.xml'
          format: 'xml'
          #failOnError: true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cobertura.xml  # Path to the coverage report
