name: Coverlet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Generate Code Coverage Report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore "WebApi/RentalManager.WebAPI/RentalManager.WebAPI.csproj"

      - name: Build the Project
        run: dotnet build --configuration Release --property WarningLevel=0 "WebApi/RentalManager.WebAPI/RentalManager.WebAPI.csproj"

      - name: Clear NuGet Cache
        run: dotnet nuget locals all --clear

      - name: Run Tests with Coverage
        run: dotnet test --results-directory WebApi/RentalManager.Tests/TestResults --collect:"XPlat Code Coverage" "WebApi/RentalManager.Tests/RentalManager.Tests.csproj"

      - name: Copy Test Results
        run: cp WebApi/RentalManager.Tests/TestResults/*/coverage.cobertura.xml ./coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: "./coverage.xml"

  Custom Badge Job:
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: test
          LABEL: 'Test?'
          STATUS: 'Yay!'
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
