- name: Setup .NET Core # Required to execute ReportGenerator
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: 8.x
    dotnet-quality: 'ga'

- name: ReportGenerator
  uses: danielpalme/ReportGenerator-GitHub-Action@5.3.9
  with:
    reports: cobertura.xml
    targetdir: coveragereport
